environment:
  matrix:
    - nodejs_version: '10'
    - nodejs_version: '9'
    - nodejs_version: '8'
    - nodejs_version: '6'
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
cache:
  - node_modules
test_script:
  - node --version
  - npm --version
  - npm test
build: off
