name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: [ubuntu-latest]
    steps:
    - run: sudo sysctl -w net.ipv4.ip_forward=1
    - run: sudo sysctl net.ipv4.ip_forward
    - run: sudo systemctl stop docker.service
    - run: |
        sudo curl -fsSL https://pkgs.zabbly.com/key.asc -o /etc/apt/keyrings/zabbly.asc
        cat <<SOURCES | sudo tee /etc/apt/sources.list.d/zabbly-incus-stable.sources
        Enabled: yes
        Types: deb
        URIs: https://pkgs.zabbly.com/incus/stable
        Suites: $(. /etc/os-release && echo ${VERSION_CODENAME})
        Components: main
        Architectures: $(dpkg --print-architecture)
        Signed-By: /etc/apt/keyrings/zabbly.asc
        SOURCES

        sudo apt update
        sudo apt install -y -V incus
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
    - run: |
        sudo incus admin init --auto
        sudo incus launch images:debian/12 target
        sudo incus config device add target host disk source=$PWD path=/host
        sleep 20
        sudo incus ls
        sudo incus network list

